import 'package:get/get.dart';

import 'flags_string.dart';

class CountyController extends GetxController {
  static CountyController get instance => Get.find();

  List country = [
    ["Afghanistan", "AF", "AFG", "004", afghanistan, "AFN"],
    ["Aland Islands", "AX", "ALA", "248", alandIslands, "null"],
    ["Albania", "AL", "ALB", "008", albania, "All"],
    ["Algeria", "DZ", "DZA", "012", algeria, "null"],
    ["American Samoa", "AS", "ASM", "016", americanSamoa, "null"],
    ["Andorra", "AD", "AND", "020", andorra, "null"],
    ["Angola", "AO", "AGO", "024", angola, "null"],
    ["Anguilla", "AI", "AIA", "660", anguilla, "null"],
    ["Antarctica", "AQ", "ATA", "010", antarctica, "null"],
    ["Antigua and Barbuda", "AG", "ATG", "028", antiguaAndBarbuda, "null"],
    ["Argentina", "AR", "ARG", "032", argentina, "ARS"],
    ["Armenia", "AM", "ARM", "051", armenia, "null"],
    ["Aruba", "AW", "ABW", "533", aruba, "AWG"],
    ["Australia", "AU", "AUS", "036", australia, "AUD"],
    ["Austria", "AT", "AUT", "040", austria, "null"],
    ["Azerbaijan", "AZ", "AZE", "031", azerbaijan, "AZN"],
    ["Bahamas", "BS", "BHS", "044", bahamas, "BSD"],
    ["Bahrain", "BH", "BHR", "048", bahrain, "null"],
    ["Bangladesh", "BD", "BGD", "050", bangladesh, "null"],
    ["Barbados", "BB", "BRB", "052", barbados, "BBD"],
    ["Belarus", "BY", "BLR", "112", belarus, "BYN"],
    ["Belgium", "BE", "BEL", "056", belgium, "null"],
    ["Belize", "BZ", "BLZ", "084", belize, "null"],
    ["Benin", "BJ", "BEN", "204", benin, "null"],
    ["Bermuda", "BM", "BMU", "060", bermuda, "BMD"],
    ["Bhutan", "BT", "BTN", "064", bhutan, "null"],
    ["Bolivia", "BO", "BOL", "068", bolivia, "BOB"],
    ["Bosnia and Herzegovina", "BA", "BIH", "070", bosniaAndHerzegovina, "BAM"],
    ["Botswana", "BW", "BWA", "072", botswana, "BWP"],
    ["Bouvet Island", "BV", "BVT", "074", bouvetIsland, "null"],
    ["Brazil", "BR", "BRA", "076", brazil, "BRL"],
    [
      "British Virgin Islands",
      "VG",
      "VGB",
      "092",
      britishVirginIslands,
      "null"
    ],
    [
      "British Indian Ocean Territory",
      "IO",
      "IOT",
      "086",
      britishIndianOceanTerritory,
      "null"
    ],
    ["Brunei Darussalam", "BN", "BRN", "096", brunei, "BND"],
    ["Bulgaria", "BG", "BGR", "100", bulgaria, "BGN"],
    ["Burkina Faso", "BF", "BFA", "854", burkinaFaso, "null"],
    ["Burundi", "BI", "BDI", "108", burundi, "null"],
    ["Cambodia", "KH", "KHM", "116", cambodia, "KHR"],
    ["Cameroon", "CM", "CMR", "120", cameroon, "null"],
    ["Canada", "CA", "CAN", "124", canada, "CAD"],
    ["Cape Verde", "CV", "CPV", "132", capeVerde, "null"],
    ["Cayman" "Islands", "KY", "CYM", "136", cayman, "KYD"],
    [
      "Central African Republic",
      "CF",
      "CAF",
      "140",
      centralAfricanRepublic,
      "null"
    ],
    ["Chad", "TD", "TCD", "148", chad, "null"],
    ["Chile", "CL", "CHL", "152", chile, "CLP"],
    ["China", "CN", "CHN", "156", china, "CNY"],
    ["Hong Kong, SAR China", "HK", "HKG", "344", hongKong, "HKD"],
    ["Macau, SAR China", "MO", "MAC", "446", macau, "null"],
    ["Christmas Island", "CX", "CXR", "162", christmasIsland, "null"],
    [
      "Cocos (Keeling) Islands",
      "CC",
      "CCK",
      "166",
      cocosKeelingIslands,
      "null"
    ],
    ["Colombia", "CO", "COL", "170", colombia, "COP"],
    ["Comoros", "KM", "COM", "174", comoros, "null"],
    ["Congo (Brazzaville)", "CG", "COG", "178", congoRepublic, "null"],
    ["Congo, (Kinshasa)", "CD", "COD", "180", congoRepublic, "null"],
    ["Cook Islands", "CK", "COK", "184", cookIslands, "null"],
    ["Costa Rica", "CR", "CRI", "188", costaRica, "CRC"],
    ["Côte d'Ivoire", "CI", "CIV", "384", cotedIvoire, "null"],
    ["Croatia", "HR", "HRV", "191", croatia, "null"],
    ["Cuba", "CU", "CUB", "192", cuba, "CUP"],
    ["Cyprus", "CY", "CYP", "196", cyprus, "null"],
    ["Czech Republic", "CZ", "CZE", "203", czechia, "CZK"],
    ["Denmark", "DK", "DNK", "208", denmark, "DKK"],
    ["Djibouti", "DJ", "DJI", "262", djibouti, "null"],
    ["Dominica", "DM", "DMA", "212", dominica, "null"],
    ["Dominican Republic", "DO", "DOM", "214", dominica, "DOP"],
    ["Ecuador", "EC", "ECU", "218", ecuador, "null"],
    ["Egypt", "EG", "EGY", "818", egypt, "EGP"],
    ["El Salvador", "SV", "SLV", "222", elSalvador, "SVC"],
    ["Equatorial Guinea", "GQ", "GNQ", "226", equatorialGuinea, "null"],
    ["Eritrea", "ER", "ERI", "232", eritrea, "null"],
    ["Estonia", "EE", "EST", "233", estonia, "null"],
    ["Ethiopia", "ET", "ETH", "231", ethiopia, "null"],
    ["Falkland Islands (Malvinas)", "FK", "FLK", "238", falkland, "FKP"],
    ["Faroe Islands", "FO", "FRO", "234", faroeIslands, "null"],
    ["Fiji", "FJ", "FJI", "242", fiji, "FJD", "null"],
    ["Finland", "FI", "FIN", "246", finland, "null"],
    ["France", "FR", "FRA", "250", france, "null"],
    ["Gabon", "GA", "GAB", "266", gabon, "null"],
    ["Gambia", "GM", "GMB", "270", gambia, "null"],
    ["Georgia", "GE", "GEO", "268", georgia, "null"],
    ["Germany", "DE", "DEU", "276", germany, "null"],
    ["Ghana", "GH", "GHA", "288", ghana, "GHS"],
    ["Greece", "GR", "GRC", "300", greece, "null"],
    ["Greenland", "GL", "GRL", "304", greenland, "null"],
    ["Grenada", "GD", "GRD", "308", grenada, "null"],
    ["Guadeloupe", "GP", "GLP", "312", france, "null"],
    ["Guam", "GU", "GUM", "316", guam, "null"],
    ["Guatemala", "GT", "GTM", "320", guatemala, "CTQ"],
    ["Guernsey", "GG", "GGY", "831", ghuernsey, "GGP"],
    ["Guinea", "GN", "GIN", "324", guinea, "null"],
    ["Guinea-Bissau", "GW", "GNB", "624", guineaBissau, "null"],
    ["Guyana", "GY", "GUY", "328", guyana, "GYD"],
    ["Haiti", "HT", "HTI", "332", haiti, "null"],
    ["Holy See (Vatican City State)", "VA", "VAT", "336", vaticanCity, "null"],
    ["Honduras", "HN", "HND", "340", honduras, "HNL"],
    ["Hungary", "HU", "HUN", "348", hungary, "HUF"],
    ["Iceland", "IS", "ISL", "352", iceland, "ISK"],
    ["India", "IN", "IND", "356", india, "INR"],
    ["Indonesia", "ID", "IDN", "360", indonesia, "IDR"],
    ["Iran, Islamic Republic of", "IR", "IRN", "364", iran, "IRR"],
    ["Iraq", "IQ", "IRQ", "368", iraq, "null"],
    ["Ireland", "IE", "IRL", "372", ireland, "null"],
    ["Isle of Man", "IM", "IMN", "833", isleOfMen, "IMP"],
    ["Israel", "IL", "ISR", "376", israel, "ILS"],
    ["Italy", "IT", "ITA", "380", italy, "null"],
    ["Jamaica", "JM", "JAM", "388", jamaica, "JMD"],
    ["Japan", "JP", "JPN", "392", japan, "JPY"],
    ["Jersey", "JE", "JEY", "832", jersey, "JEP"],
    ["Jordan", "JO", "JOR", "400", jordan, "null"],
    ["Kazakhstan", "KZ", "KAZ", "398", kazakhstan, "KZT"],
    ["Kenya", "KE", "KEN", "404", kenya, "null"],
    ["Kiribati", "KI", "KIR", "296", kiribati, "null"],
    ["Korea (North)", "KP", "PRK", "408", northKorea, "KPW"],
    ["Korea (South)", "KR", "KOR", "410", southKorea, "KRW"],
    ["Kuwait", "KW", "KWT", "414", kuwait, "null"],
    ["Kyrgyzstan", "KG", "KGZ", "417", kyrgyzstan, "KGS"],
    ["Lao PDR", "LA", "LAO", "418", laos, "LAK"],
    ["Latvia", "LV", "LVA", "428", latvia, "null"],
    ["Lebanon", "LB", "LBN", "422", lebanon, "LBP"],
    ["Lesotho", "LS", "LSO", "426", lesotho, "null"],
    ["Liberia", "LR", "LBR", "430", liberia, "LRD"],
    ["Libya", "LY", "LBY", "434", libya, "null"],
    ["Liechtenstein", "LI", "LIE", "438", liechtenstein, "null"],
    ["Lithuania", "LT", "LTU", "440", lithuania, "null"],
    ["Luxembourg", "LU", "LUX", "442", luxembourg, "null"],
    ["Macedonia", "MK", "MKD", "807", northMacedonia, "MKD"],
    ["Madagascar", "MG", "MDG", "450", madagascar, "null"],
    ["Malawi", "MW", "MWI", "454", malawi, "null"],
    ["Malaysia", "MY", "MYS", "458", malaysia, "MYR"],
    ["Maldives", "MV", "MDV", "462", maldives, "null"],
    ["Mali", "ML", "MLI", "466", mali, "null"],
    ["Malta", "MT", "MLT", "470", malta, "null"],
    ["Marshall Islands", "MH", "MHL", "584", marshallIslands, "null"],
    ["Mauritania", "MR", "MRT", "478", mauritania, "null"],
    ["Mauritius", "MU", "MUS", "480", mauritius, "MUR"],
    ["Mexico", "MX", "MEX", "484", mexico, "MXN"],
    ["Micronesia, Federated States of", "FM", "FSM", "583", micronesia, "null"],
    ["Moldova", "MD", "MDA", "498", moldova, "null"],
    ["Monaco", "MC", "MCO", "492", monaco, "null"],
    ["Mongolia", "MN", "MNG", "496", mongolia, "MNT"],
    ["Montenegro", "ME", "MNE", "499", montenegro],
    ["Morocco", "MA", "MAR", "504", morocco, "null"],
    ["Mozambique", "MZ", "MOZ", "508", mozambique, "MZN"],
    ["Myanmar", "MM", "MMR", "104", myanmar, "null"],
    ["Namibia", "NA", "NAM", "516", namibia, "NAD"],
    ["Nauru", "NR", "NRU", "520", naura, "null"],
    ["Nepal", "NP", "NPL", "524", nepal, "NPR"],
    ["Netherlands", "NL", "NLD", "528", netherlands, "ANG"],
    ["New Zealand", "NZ", "NZL", "554", newZealand, "NZd"],
    ["Nicaragua", "NI", "NIC", "558", nicaragua, "NIO"],
    ["Niger", "NE", "NER", "562", niger, "null"],
    ["Nigeria", "NG", "NGA", "566", nigeria, "NGN"],
    ["Norway", "NO", "NOR", "578", norway, "NOK"],
    ["Oman", "OM", "OMN", "512", oman, "OMR"],
    ["Pakistan", "PK", "PAK", "586", pakistan, "PKR"],
    ["Palau", "PW", "PLW", "585", palau, "null"],
    ["Palestinian Territory", "PS", "PSE", "275", palestine, "null"],
    ["Panama", "PA", "PAN", "591", panama, "PAB"],
    ["Papua New Guinea", "PG", "PNG", "598", papuaNewGuinea, "null"],
    ["Paraguay", "PY", "PRY", "600", paraguay, "PYG"],
    ["Peru", "PE", "PER", "604", peru, "PEN"],
    ["Philippines", "PH", "PHL", "608", philippines, "PHP"],
    ["Poland", "PL", "POL", "616", poland, "PLN"],
    ["Portugal", "PT", "PRT", "620", portugal, "null"],
    ["Puerto Rico", "PR", "PRI", "630", puertoRico, "null"],
    ["Qatar", "QA", "QAT", "634", qatar, "QAR"],
    ["Romania", "RO", "ROU", "642", romania, "RON"],
    ["Russian Federation", "RU", "RUS", "643", russia, "RUB"],
    ["Rwanda", "RW", "RWA", "646", rwanda, "null"],
    ["Saint Kitts and Nevis", "KN", "KNA", "659", saintKittsNevis, "null"],
    ["Saint Lucia", "LC", "LCA", "662", saintLucia, "null"],
    [
      "Saint Vincent and Grenadines",
      "VC",
      "VCT",
      "670",
      saintVincentGrenadines,
      "null"
    ],
    ["Samoa", "WS", "WSM", "882", samoa, "null"],
    ["San Marino", "SM", "SMR", "674", sanMarino, "null"],
    ["Sao Tome and Principe", "ST", "STP", "678", saoTomePrincipe, "null"],
    ["Saudi Arabia", "SA", "SAU", "682", saudiArabia, "SAR"],
    ["Senegal", "SN", "SEN", "686", senegal, "null"],
    ["Serbia", "RS", "SRB", "688", serbia, "RSD"],
    ["Seychelles", "SC", "SYC", "690", seychelles, "SCR"],
    ["Sierra Leone", "SL", "SLE", "694", sierraLeone, "null"],
    ["Singapore", "SG", "SGP", "702", singapore, "SGD"],
    ["Slovakia", "SK", "SVK", "703", slovakia, "null"],
    ["Slovenia", "SI", "SVN", "705", slovenia, "null"],
    ["Solomon Islands", "SB", "SLB", "090", solomonIslands, "SBD"],
    ["Somalia", "SO", "SOM", "706", somalia, "SOS"],
    ["South Africa", "ZA", "ZAF", "710", southAfrica, "ZAR"],
    ["South Sudan", "SS", "SSD", "728", southSudan, "null"],
    ["Spain", "ES", "ESP", "724", spain, "null"],
    ["Sri Lanka", "LK", "LKA", "144", sriLanka, "LKR"],
    ["Sudan", "SD", "SDN", "736", sudan, "null"],
    ["Suriname", "SR", "SUR", "740", suriname, "null"],
    ["Sweden", "SE", "SWE", "752", sweden, "SEK"],
    ["Switzerland", "CH", "CHE", "756", switzerland, "CHF"],
    ["Syrian Arab Republic (Syria)", "SY", "SYR", "760", syria, "SYP"],
    ["Taiwan, Republic of China", "TW", "TWN", "158", taiwan, "TWD"],
    ["Tajikistan", "TJ", "TJK", "762", tajikistan, "null"],
    ["Tanzania, United Republic of", "TZ", "TZA", "834", tanzania, "null"],
    ["Thailand", "TH", "THA", "764", thailand, "THB"],
    ["Timor-Leste", "TL", "TLS", "626", timorLeste, "null"],
    ["Togo", "TG", "TGO", "768", togo, "null"],
    ["Tonga", "TO", "TON", "776", tongo, "null"],
    ["Trinidad and Tobago", "TT", "TTO", "780", trinidadTobago, "TTD"],
    ["Tunisia", "TN", "TUN", "788", tunisia, "null"],
    ["Turkey", "TR", "TUR", "792", turkey, "TRY"],
    ["Turkmenistan", "TM", "TKM", "795", turkmenistan, "null"],
    ["Tuvalu", "TV", "TUV", "798", tuvalu, "TVD"],
    ["Uganda", "UG", "UGA", "800", uganda, "null"],
    ["Ukraine", "UA", "UKR", "804", ukraine, "UAH"],
    ["United Arab Emirates", "AE", "ARE", "784", unitedArabEmirates, "null"],
    ["United Kingdom", "GB", "GBR", "826", unitedKingdom, "GBP"],
    [
      "United States of America",
      "US",
      "USA",
      "840",
      unitedStatesAmerica,
      "USD"
    ],
    ["Uruguay", "UY", "URY", "858", uruguay, "UYU"],
    ["Uzbekistan", "UZ", "UZB", "860", uzbekistan, "UZS"],
    ["Vanuatu", "VU", "VUT", "548", vanuatu, "null"],
    ["Venezuela (Bolivian Republic)", "VE", "VEN", "862", venezuela, "VEF"],
    ["Viet Nam", "VN", "VNM", "704", vietnam, "VND"],
    ["Virgin Islands, US", "VI", "VIR", "850", britishVirginIslands, "null"],
    ["Yemen", "YE", "YEM", "887", yemen, "YER"],
    ["Zambia", "ZM", "ZMB", "894", zambia, "null"],
    ["Zimbabwe", "ZW", "ZWE", "716", zimbabwe, "ZWD"],
    ["Gold", "null", "null", "null", gold, " XAU"],
    ["Europe", "null", "null", "null", europe, " EUR"],
  ];

  List currencies = [
    ["AUD", australia],
    ["CAD", canada],
    ["CHF", switzerland],
    ["EUR", europe],
    ["GBP", unitedKingdom],
    ["JPY", japan],
    ["NZD", newZealand],
    ["USD", unitedStatesAmerica],
    ["XAU", gold],
  ];

  String getCountryByCode(String code) {
    for (final c in country) {
      if (c[3] == code) {
        return c[0];
      }
    }
    return 'Unknown Country';
  }

  String getCountryByAlpha_2(String alpha_2) {
    for (final c in country) {
      if (c[1] == alpha_2) {
        return c[0];
      }
    }
    return 'Unknown Country';
  }

  String getCountryByAlpha_3(String alpha_3) {
    for (final c in country) {
      if (c[2] == alpha_3) {
        return c[0];
      }
    }
    return 'Unknown Country';
  }

  String getCurrencyFlagBySym(String symbol) {
    for (final currency in currencies) {
      if (currency[0] == symbol) {
        return currency[1];
      }
    }
    return world;
  }
}
/* */
